name: Update .github/dependabot.yml

on:
  push:
    paths:
      - .github/workflows/dependabot.yml
      - recipes/dependabot.rb

env:
  NAMESPACE: sue445
  ASSIGNEE:  sue445

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:
          - repo: activerecord-compatible_legacy_migration
          - repo: activerecord-simple_index_name
          - repo: apple_system_status
          - repo: capistrano-around_chatwork
          - repo: capistrano-itamae
          - repo: chatwork_webhook_verify
          - repo: condo3
          - repo: connpass_api_v2-ruby
          - repo: cure-mastodon-bots
          - repo: cure_line
          - repo: datadog_thread_tracer
          - repo: date_discreter
          - repo: dockerfile-awscli-all
          - repo: dockerfile-heroku-cli
          - repo: dockerfile-packer-serverspec
          - repo: dockerhub-slack-webhook
          - repo: doorkeeper_jp
          - repo: emoy_webhook
          - repo: faker-precure
          - repo: faker-pretty_series
          - repo: faraday-mashify
          - repo: faraday_boolean
          - repo: feed_squeezer
          - repo: fluent-plugin-chatwork
          - repo: funnel_http
          - repo: gcp-kmsenv
          - repo: gcp-secretmanagerenv
          - repo: gitlab_mr_release
          - repo: gitpanda
          - repo: go-doorkeeper
          - repo: google_holiday_calendar
          - repo: index_shotgun
          - repo: itamae-plugin-recipe-consul
          - repo: itamae-plugin-recipe-git_now
          - repo: itamae-plugin-recipe-gitlab_runner
          - repo: itamae-plugin-recipe-tig
          - repo: itamae-plugin-recipe-tmux
          - repo: itamae-plugin-resource-encrypted_remote_file
          - repo: itest5ch
          - repo: kagaribi
          - repo: kiriban_getter
          - repo: mysql2-nested_hash_bind
          - repo: omniauth-chatwork
          - repo: pixela
          - repo: plant_erd
          - repo: precure-birthday-calendar
          - repo: pretty-all-friends-birthday-calendar
          - repo: pribirthdaybot
          - repo: prismdb-ruby
          - repo: regional-rb-calendar
          - repo: rspec-temp_dir
          - repo: rspec-time_stop
          - repo: rubicure
          - repo: rubicure-playground
          - repo: rubocop-isucon
          - repo: rubocop-itamae
          - repo: rubocop_auto_corrector
          - repo: sashimi_tanpopo
          - repo: sashimi_tanpopo-personal
          - repo: sashimi_tanpopo_action
          - repo: sengiri_yaml
          - repo: syobocalite
          - repo: terraform-version-updater
          - repo: tweet_pixels
          - repo: workflows
          - repo: x_post_sanitizer
          - repo: zatsu_monitor

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id:       ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ env.NAMESPACE }}
          repositories: ${{ matrix.repo }}

      - name: checkout target repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ env.NAMESPACE }}/${{ matrix.repo }}
          token:      ${{ steps.generate_token.outputs.token }}
          path:       tmp/repo/

      - run: ls -la tmp/repo/

      - name: Generate arguments
        run: |
          set -xe
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            dry_run="false"
          else
            dry_run="true"
          fi
          echo "DRY_RUN=${dry_run}" >> $GITHUB_ENV

      - uses: sue445/sashimi_tanpopo_action@abcea180dfe1ff3947b8c34b1cd77a0c2b940bb1 # v0.5.1
        with:
          recipe-files:         "${{ github.workspace }}/recipes/dependabot.rb"
          target-dir:           "${{ github.workspace }}/tmp/repo"
          dry-run:              "${{ env.DRY_RUN }}"
          github-repository:    "${{ env.NAMESPACE }}/${{ matrix.repo }}"
          message:              "Update .github/dependabot.yml :dependabot: [ci skip]"
          pr-title:             "Update .github/dependabot.yml :dependabot:"
          pr-body:              "ref. https://github.com/sue445/sashimi_tanpopo-personal/commit/${{ github.sha }}"
          pr-source-branch:     "update_dependabot_yml"
          pr-assignees:         "${{ env.ASSIGNEE }}"
          pr-labels:            "chore"
          only-changes-summary: "true"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Slack Notification (not success)
        uses: act10ns/slack@cfcc30955fe9377f4f55e1079e5419ee1014269f # v2
        if: "! success()"
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          matrix: ${{ toJson(matrix) }}

  notify:
    needs:
      - build

    runs-on: ubuntu-slim

    steps:
      - name: Slack Notification (success)
        uses: act10ns/slack@cfcc30955fe9377f4f55e1079e5419ee1014269f # v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
