name: terraform_upgrade_myself_version

on:
  push:
    paths:
      - .github/workflows/terraform_upgrade_myself_version.yml
      - recipes/terraform_upgrade_myself_version.rb
      - misc/print_latest_terraform_version.rb
      - misc/terraform_helper.rb
    branches-ignore:
      - main

  schedule:
    - cron: "0 10 * * 5" # JST 19:00 (Fri)
  workflow_dispatch:

env:
  NAMESPACE: sue445
  ASSIGNEE:  sue445

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: true

      - uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1.268.0
        with:
          ruby-version: ruby

      - name: Set envs
        run: |
          set -xe
          GH_REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d/ -f2)
          echo "GH_REPO_NAME=${GH_REPO_NAME}" >> $GITHUB_ENV
          
          LATEST_TERRAFORM=$(ruby ./misc/print_latest_terraform_version.rb)
          echo "LATEST_TERRAFORM=${LATEST_TERRAFORM}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        with:
          app-id:       ${{ secrets.GH_APP_ID }}
          private-key:  ${{ secrets.GH_PRIVATE_KEY }}
          owner:        ${{ env.NAMESPACE }}
          repositories: ${{ env.GH_REPO_NAME }}

      - name: Generate arguments
        run: |
          set -xe
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            dry_run="false"
          else
            dry_run="true"
          fi
          echo "DRY_RUN=${dry_run}" >> $GITHUB_ENV

      - uses: sue445/sashimi_tanpopo_action@c317a33b9544000c538baa14a508345e7d4bb1c2 # v0.5.0
        with:
          recipe-files:         "${{ github.workspace }}/recipes/terraform_upgrade_myself_version.rb"
          target-dir:           "${{ github.workspace }}"
          dry-run:              "${{ env.DRY_RUN }}"
          github-repository:    "${{ env.NAMESPACE }}/${{ env.GH_REPO_NAME }}"
          message:              "Upgrade to Terraform ${{ env.LATEST_TERRAFORM }}"
          pr-title:             "Upgrade to Terraform ${{ env.LATEST_TERRAFORM }}"
          pr-body:              "ref. https://github.com/sue445/sashimi_tanpopo-personal/commit/${{ github.sha }}"
          pr-source-branch:     "terraform_${{ env.LATEST_TERRAFORM }}"
          pr-assignees:         "${{ env.ASSIGNEE }}"
          only-changes-summary: "true"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Slack Notification
        uses: act10ns/slack@cfcc30955fe9377f4f55e1079e5419ee1014269f # v2
        if: always()
        continue-on-error: true
        with:
          status: ${{ job.status }}
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
